package com.zqxsober.dao.general;

import com.zqxsober.domain.RcAreaCode;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface RcAreaCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rc_area_code
     *
     * @mbggenerated Thu Sep 21 14:38:32 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer rcAreaCodeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rc_area_code
     *
     * @mbggenerated Thu Sep 21 14:38:32 GMT+08:00 2017
     */
    int insert(RcAreaCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rc_area_code
     *
     * @mbggenerated Thu Sep 21 14:38:32 GMT+08:00 2017
     */
    int insertSelective(RcAreaCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rc_area_code
     *
     * @mbggenerated Thu Sep 21 14:38:32 GMT+08:00 2017
     */
    RcAreaCode selectByPrimaryKey(Integer rcAreaCodeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rc_area_code
     *
     * @mbggenerated Thu Sep 21 14:38:32 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(RcAreaCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rc_area_code
     *
     * @mbggenerated Thu Sep 21 14:38:32 GMT+08:00 2017
     */
    int updateByPrimaryKey(RcAreaCode record);
}